name: "nightly build-jdk nightly"
on:
  push:
    branches-ignore:
      - '**'
jobs:
  hotspot14:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        impl: [temurin]
        buildlist: [openjdk]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.version }}
        distribution: ${{ matrix.impl }}
    - name: AQA
      uses: adoptium/run-aqa@v2
      with: 
        version: ${{ matrix.version }}
        jdksource: 'customized'
        build_list: ${{ matrix.buildlist}}
        target: '_jvm_compiler'
