name: "build-jdk with adoptopenjdk openjdk-build hotspot"
on: # rebuild any PRs and main branch changes
  push:
    #branches-ignore:
     # - '**'
jobs:
#   job1testopoenj9:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: false
#       matrix:
#         os: [windows-2016]
#     steps:
#     - uses: actions/checkout@v1
#     - uses: sophia-guo/build-jdk@winnew
#       id: buildJDK
#       with: 
#         javaToBuild: 'jdk14u'
#         impl: 'openj9'
#     - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version
#     - uses: actions/upload-artifact@v2
#       with:
#         name: buildJDK
#         path: ./**/artifacts/*.zip/

  job2testhotspot:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016]
    steps:
    - uses: actions/checkout@v1
    - uses: sophia-guo/build-jdk@winnew
      id: buildJDK
      with: 
        javaToBuild: 'jdk14u'
    - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version
    - uses: actions/upload-artifact@v2
      with:
        name: buildJDK
        path: ./**/artifacts/*.zip/