name: "place holder for example"
on:
  push:
    # branches-ignore:
    #   - '**'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016] #[ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: sophia-guo/build-jdk-openj9@win
      id: buildJDK
      with: 
        version: 11
    - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version
    - run: printenv