name: "build-jdk with adoptopenjdk openjdk-build hotspot"
on: # rebuild any PRs and main branch changes
  push:
jobs:
  hotspot11:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016]
    steps:
    - uses: actions/checkout@v1
    - uses: AdoptOpenJDK/install-jdk@v1  
      with:
        version: '11'
        source: 'nightly'
    - name: AQA
      uses: AdoptOpenJDK/run-aqa@master
      with: 
        version: '11'
        jdksource: 'install-jdk'
        build_list: 'openjdk'
        target: '_jdk_custom'
